### ISSUE TITLE
I can't find how to write the question, I only see the choices

### ISSUE THREAD

**Issue by AnopheliaMiratio** [ale18V/Anki-Multiple-Choice#2]
I followed your instructions to use template 2. My problem is that I also wrote the question the answers correspond to in the Front but it doesn't show.

Also, is it possible to have less than 4 potential answers somehow?

**Comment by ale18V** [comment]
You have to **add** the content of `front.html` and `back.html` to your card model and should not remove what's already there. You just paste the content of those files wherever you want the multiple choice boxes to pop up.

To address your second question: yes it's possible to have as few and as many as you want. Every line containing this code in your card:`<div class="multiple-choice-button">none</div>` corresponds to a multiple choice box so if you want 2 choices just have 2 of them instead of 4.
